// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlqwgqzwluhiwrfmexvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscXdncXp3bHVoaXdyZm1leHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDU1MTMsImV4cCI6MjA2NTQ4MTUxM30.31F00WHaqraS_5wo6YHA3ihajksBoQwcbNh1HAQ2Sxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);